### PR TITLE
Env settings in config file

### PR DESCRIPTION
**Pull request by PendoNL**
Laravel has the Pusher settings by default in the .env file, updated the config/pusher.php file to use these settings by default.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
👎 You should just add these in your own app and publish the config file.

**Comment by PendoNL** [comment]
I'm not sure if I understand what you mean? Isn't it bad practice to have these keys stored in the config/pusher.php file? That will potentially save them in your version control, doesn't it?

**Comment by GrahamCampbell** [comment]
No, I'm saying you should make these env changes in your published config file.

**Comment by vinkla** [comment]
Tanka for the pull request @PendoNL but in this case I agree with @GrahamCampbell.

**Comment by PendoNL** [comment]
Just out of curiosity (I respect your decision), but why let people do this manually when Laravel uses these .env vars out of the box? I understand that the generated config file needs to be editted anyway for other settings, is that the reason?

Anyway, thanks for the Laravel bridge! Very easy to use!

**Comment by vinkla** [comment]
@PendoNL mostly since we don't want to force anyone to use the `env` out of the box. Also as you say, the config has to be updated anyway.

**Comment by PendoNL** [comment]
Alright, point taken! Thanks for explaining.

**Pull request closed without merging**
